name: build-and-validate

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        java-version: ['17', '21','25']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: java-setup
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'
      - name: build (unix)
        if: runner.os != 'Windows'
        run: ./gradlew build
      - name: build (windows)
        if: runner.os == 'Windows'
        run: ./gradlew.bat build
